#!/bin/bash
#SBATCH -N 1 --ntasks-per-node 128
#SBATCH -t 00:60:00
#SBATCH -p RM-small
#SBATCH -J 'RM'

module load gcc
source /jet/home/susa/pkgs/gromacs/2020.5/bin/GMXRC

export GMX_MAXBACKUP=-1  # do not make back-ups

#gmx mdrun -v -s ../npt.tpr -o npt -g  N1_nt128.log -nt 128  -ntomp 1
#gmx mdrun -v -s ../npt.tpr -o npt -g  N1_nt64.log -nt 64  -ntomp 1
#gmx mdrun -v -s ../npt.tpr -o npt -g  N1_nt32.log -nt 32  -ntomp 1
#gmx mdrun -v -s ../npt.tpr -o npt -g  N1_nt16.log -nt 16  -ntomp 1
#gmx mdrun -v -s ../npt.tpr -o npt -g  N1_nt8.log -nt 8  -ntomp 1
#gmx mdrun -v -s ../npt.tpr -o npt -g  N1_nt4.log -nt 4  -ntomp 1
#gmx mdrun -v -s ../npt.tpr -o npt -g  N1_nt2.log -nt 2  -ntomp 1
gmx mdrun -v -s ../npt.tpr -o npt -g  N1_nt1.log -nt 1  -ntomp 1

             
