#!/bin/bash
#SBATCH -N 1 --ntasks-per-node 128
#SBATCH -t 00:60:00
#SBATCH -p RM-small
#SBATCH -J 'RM'


module load gcc/10.2.0
module load openmpi/3.1.6-gcc10.2.0
source /jet/home/susa/pkgs/gromacs/2020.5_cpu/bin/GMXRC

export GMX_MAXBACKUP=-1  # do not make back-ups

#mpirun -np 128 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  N1_np128.log  -ntomp 1
#mpirun -np 64 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  N1_np64.log  -ntomp 1
#mpirun -np 32 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  N1_np32.log  -ntomp 1
#mpirun -np 16 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  N1_np16.log  -ntomp 1
#mpirun -np 8 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  N1_np8.log  -ntomp 1
#mpirun -np 4 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  N1_np4.log  -ntomp 1
#mpirun -np 2 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  N1_np2.log  -ntomp 1
mpirun -np 1 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  N1_np1.log  -ntomp 1

             






